### ISSUE TITLE
set default payment method

### ISSUE THREAD

**Issue by edkoma** [nyu-devops-payments-2017/payments#10]
**As a** ...  User
**I need** ...  to be able to set one of my payment method as default payment method
**So that** ...  I don't have to choose my payment method every time I check out

**Assumptions:** 
*There is an attribute in payment method table that says "is_default".

**Acceptance Criteria:**

Given ... I have at least one payment method saved
When ... I click a button marked "set as default"
Then ... I should make a 'PATCH /payments/methods/<id>/' call and set is_default for that payment method to True and set is_default for the previous default to False

**Comment by edkoma** [comment]
Same problem with issue #8 , there's no table for payment methods with details, so there's no point setting 1/2/3 to default.

**Comment by jordanagreen** [comment]
I'll turn payment method from an enum into a model (which I honestly should have done from the start) and implement a /setDefault action.
