### ISSUE TITLE
Add config files for Bluemix

### ISSUE THREAD

**Issue by jordanagreen** [nyu-devops-payments-2017/payments#37]
**As a** developer 
**I need** My application to be configured for Bluemix  
**So that** I can have continuous deployment to the cloud in my pipeline.  

**Assumptions:** 
* ...

**Acceptance Criteria:**
```We have working manifest.yml, Procfile, and runtime.txt

Given I have the required config files set up correctly
When I use `cf push`
Then my app should be deployed to Bluemix as specified in the config files.
```

**Comment by rohit-masur** [comment]
Should include only runtime.txt and Procfile in this user story as manifest.yml file is specific to the bluemix host, name and domain data. I am creating a different user story for creation of manifest.yml.
