### ISSUE TITLE
Delete payment method

### ISSUE THREAD

**Issue by ghost** [nyu-devops-payments-2017/payments#6]
**As a**  user
**I need** to remove a payment method
**So that** I can remove my payment information when I no longer want it in the system.
**Assumptions:**

- A list of payment methods currently exists, in a database or configuration file. 

**Acceptance Criteria:**
```
Given there is at least one payment method. 
When I call 'DELETE /payments/methods/id'
Then I should I get a message saying that the payment method was deleted from the table. 
 ```

**Comment by rohit-masur** [comment]
As a user, I think we can at most change his payment method not delete it entirely. Deleting a Payment method as mentioned in the user story will delete the payment method globally.
