### ISSUE TITLE
retrieve saved payment methods

### ISSUE THREAD

**Issue by edkoma** [nyu-devops-payments-2017/payments#7]
**As a Buyer**
**I need** to see my saved payment methods
**So that** I can use my saved payment methods to pay without enter same information again

**Assumptions:**
There is a table of saved payment methods associated with Buyer ID.

**Acceptance Criteria:**
When I call `GET /userID/saved_payment_methods`
I will get a list of saved payment methods associated with my id

**Comment by jordanagreen** [comment]
Duplicate of #5
